favicon: null
name: 'Andiamo!'
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2531328
  brandStrength: 0.7921147
  lightness: 0.3088973
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.4630326
typography_spectrum: 0.3677945
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2224311
analytics:
  twitter: null
  google: null
  facebook: null
