name: 'Andiamo!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02935
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Andiamo! at Al Zeina, located at Raha Beach Road in Abu Dhabi is the top address for fresh and contemporary Italian Style food. Only fresh ingredients, prepared when you order are the basis for the best Pizza and Pasta in town.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16263f'
    - '#fefefe'
    - '#5d686c'
    - '#a6a8a7'
    - '#b5e415'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
